title: Koopman-Assisted Reinforcement Learning
description: Fusing Koopman operators with maximum entropy RL algorithms
show_downloads: true
email: pwr36@cornell.edu
github_username: pdbz199
theme: jekyll-theme-cayman